CREATE TABLE work.w_business_audit_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entity_type VARCHAR(40) NOT NULL,
    entity_id BIGINT NOT NULL,
    action_code VARCHAR(60) NOT NULL,
    actor_user_id BIGINT,
    actor_name VARCHAR(160),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    changes_json TEXT NOT NULL
);
CREATE INDEX ix_business_audit_created ON work.w_business_audit_log(created_at DESC,id DESC);
CREATE INDEX ix_business_audit_entity ON work.w_business_audit_log(entity_type,entity_id,created_at DESC);
CREATE INDEX ix_business_audit_actor ON work.w_business_audit_log(actor_user_id,created_at DESC);
COMMENT ON TABLE work.w_business_audit_log IS 'Неизменяемый журнал критических бизнес-действий, записываемый в транзакции изменения';
COMMENT ON COLUMN work.w_business_audit_log.id IS 'Идентификатор записи';
COMMENT ON COLUMN work.w_business_audit_log.entity_type IS 'Тип изменённой сущности';
COMMENT ON COLUMN work.w_business_audit_log.entity_id IS 'Идентификатор изменённой сущности';
COMMENT ON COLUMN work.w_business_audit_log.action_code IS 'Код бизнес-действия';
COMMENT ON COLUMN work.w_business_audit_log.actor_user_id IS 'Автор, NULL для системного вызова без установленного пользователя';
COMMENT ON COLUMN work.w_business_audit_log.actor_name IS 'Имя автора на момент действия';
COMMENT ON COLUMN work.w_business_audit_log.created_at IS 'Время записи';
COMMENT ON COLUMN work.w_business_audit_log.changes_json IS 'JSON со снимками до и после; только разрешённые бизнес-поля без паролей, токенов и файлов';
CREATE FUNCTION work.reject_business_audit_mutation() RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
    RAISE EXCEPTION 'Business audit entries cannot be updated or deleted';
END;
$$;
CREATE TRIGGER business_audit_immutable BEFORE UPDATE OR DELETE ON work.w_business_audit_log
FOR EACH ROW EXECUTE FUNCTION work.reject_business_audit_mutation();
