<template>
  <section class="section-wrap entity-page">
    <Breadcrumbs :items="[{ label: 'Туры', to: { path: '/', query: route.query } }, { label: competition?.name || 'Соревнование' }]" />
    <UiState v-if="loading" tone="loading" title="Загружаем соревнование" />
    <UiState v-else-if="error" tone="error" title="Не удалось загрузить соревнование" :message="error" />
    <template v-else-if="competition">
      <article class="card entity-hero"><div><p class="eyebrow">{{ competition.type === 'CUP' ? 'Кубок' : 'Чемпионат' }}</p><h1>{{ competition.name }}</h1><p class="muted-text">{{ competition.status }}</p></div><div class="actions-row"><RouterLink class="btn-primary" :to="{path:'/',query:{season:route.params.seasonId,competition:route.params.competitionId}}">Матчи и таблица</RouterLink><RouterLink class="btn-ghost" :to="{path:'/league',query:{season:route.params.seasonId,competition:route.params.competitionId}}">Регламент</RouterLink></div></article>
      <div class="entity-columns">
        <article class="card entity-panel"><h2>Участники</h2><div class="entity-list"><RouterLink v-for="team in overview.teams || []" :key="team.id" :to="'/teams/'+team.id">{{ team.name }}</RouterLink><p v-if="!overview.teams?.length" class="muted-text">Участники пока не опубликованы.</p></div></article>
        <article class="card entity-panel"><h2>Таблица</h2><div class="entity-list"><RouterLink v-for="row in (overview.standings || []).slice(0,8)" :key="row.teamId" :to="'/teams/'+row.teamId"><b>{{ row.position }}</b> {{ row.teamName }} <span>{{ row.points }} оч.</span></RouterLink><p v-if="!overview.standings?.length" class="muted-text">Таблица пока не рассчитана.</p></div></article>
      </div>
      <article class="card entity-panel"><h2>Календарь</h2><div class="entity-list"><template v-for="tour in competitionTours" :key="tour.id"><RouterLink v-for="match in tour.matches || []" :key="match.id" :to="'/matches/'+match.id">{{ match.homeTeamName }} — {{ match.awayTeamName }} <span>{{ match.kickoffAt ? new Date(match.kickoffAt).toLocaleString('ru-RU') : 'Дата уточняется' }}</span></RouterLink></template><p v-if="!competitionTours.length" class="muted-text">Матчи пока не опубликованы.</p></div></article>
      <article v-if="regulation" class="card entity-panel"><h2>Регламент</h2><a class="btn-ghost" :href="apiBaseUrl+regulation.downloadUrl" target="_blank" rel="noopener">Скачать PDF</a></article>
      <article class="card entity-panel"><h2>Лидеры статистики</h2><div class="home-ranking"><RouterLink v-for="row in stats.slice(0,10)" :key="row.playerId" :to="'/players/'+row.playerId"><b>{{ row.goals || 0 }}</b><strong>{{ row.playerName }}</strong><span>{{ row.teamName }}</span></RouterLink><p v-if="!stats.length" class="muted-text">Статистика пока не опубликована.</p></div></article>
    </template>
  </section>
</template>
<script setup>
import {computed,onMounted,ref} from 'vue';import{useRoute}from'vue-router';import Breadcrumbs from'../components/Breadcrumbs.vue';import UiState from'../components/UiState.vue';import{useAuth}from'../store/auth';import{createCompetitionsApi}from'../api/competitions';import{createCatalogApi}from'../api/catalog'
const route=useRoute();const{optionalAuthApiRequest}=useAuth();const api=createCompetitionsApi(optionalAuthApiRequest);const catalog=createCatalogApi(optionalAuthApiRequest);const competition=ref(null);const stats=ref([]);const overview=ref({});const regulations=ref([]);const loading=ref(true);const error=ref('');const apiBaseUrl=import.meta.env.VITE_API_BASE_URL||'http://127.0.0.1:8080'
const competitionTours=computed(()=>(overview.value.tours||[]).filter(t=>!t.competitionId||String(t.competitionId)===String(route.params.competitionId)));const regulation=computed(()=>regulations.value.find(x=>x.targetType==='COMPETITION'&&String(x.targetId)===String(route.params.competitionId)))
onMounted(async()=>{try{const[items,statRows,seasonOverview,documents]=await Promise.all([api.list(route.params.seasonId),optionalAuthApiRequest('/api/seasons/'+route.params.seasonId+'/competitions/'+route.params.competitionId+'/player-stats',{method:'GET'}),catalog.getSeasonOverview(route.params.seasonId),catalog.getLeagueRegulations()]);competition.value=items.find(x=>String(x.id)===String(route.params.competitionId));if(!competition.value)throw new Error('Соревнование не найдено.');stats.value=statRows;overview.value=seasonOverview;regulations.value=documents}catch(e){error.value=e.message}finally{loading.value=false}})
</script>
<style scoped>.entity-page{display:grid;gap:18px}.entity-hero{display:flex;justify-content:space-between;align-items:end;gap:20px;padding:32px}.entity-hero h1{margin:6px 0;font-size:clamp(2rem,4vw,3.5rem)}.entity-panel{padding:24px}.entity-columns{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:18px}.entity-list,.home-ranking{display:grid}.entity-list>a,.home-ranking>a{display:grid;grid-template-columns:auto 1fr auto;gap:12px;padding:13px;border-bottom:1px solid var(--line)}.entity-list span,.home-ranking span{color:var(--muted);text-align:right}.home-ranking b{color:var(--brand)}@media(max-width:650px){.entity-hero{align-items:start;flex-direction:column}.entity-columns{grid-template-columns:1fr}.entity-list>a{grid-template-columns:1fr}.entity-list span{text-align:left}}</style>
